import type { SystemCode, SystemInfo } from '@/types/system';

// Registry of systems ROMie supports.
export const SYSTEM_REGISTRY: Partial<Record<SystemCode, SystemInfo>> = {
  // === NINTENDO CONSOLES ===
  nes: {
    code: 'nes',
    displayName: 'NES',
    fullName: 'Nintendo Entertainment System',
    type: 'console',
    extensions: ['.nes'],
    requiresBios: false,
    manufacturer: 'Nintendo',
    releaseYear: 1985,
  },
  snes: {
    code: 'snes',
    displayName: 'SNES',
    fullName: 'Super Nintendo Entertainment System',
    type: 'console',
    extensions: ['.sfc', '.snes', '.smc'],
    requiresBios: false,
    manufacturer: 'Nintendo',
    releaseYear: 1990,
  },
  n64: {
    code: 'n64',
    displayName: 'N64',
    fullName: 'Nintendo 64',
    type: 'console',
    extensions: ['.n64', '.v64', '.z64'],
    requiresBios: false,
    manufacturer: 'Nintendo',
    releaseYear: 1996,
  },

  // === NINTENDO HANDHELDS ===
  vb: {
    code: 'vb',
    displayName: 'Virtual Boy',
    fullName: 'Nintendo Virtual Boy',
    type: 'console',
    extensions: ['.vb'],
    requiresBios: false,
    manufacturer: 'Nintendo',
    releaseYear: 1995,
  },
  gb: {
    code: 'gb',
    displayName: 'Game Boy',
    fullName: 'Nintendo Game Boy',
    type: 'handheld',
    extensions: ['.gb', '.dmg'],
    requiresBios: false,
    manufacturer: 'Nintendo',
    releaseYear: 1989,
  },
  gbc: {
    code: 'gbc',
    displayName: 'Game Boy Color',
    fullName: 'Nintendo Game Boy Color',
    type: 'handheld',
    extensions: ['.gbc', '.gb'],
    requiresBios: false,
    manufacturer: 'Nintendo',
    releaseYear: 1998,
  },
  gba: {
    code: 'gba',
    displayName: 'Game Boy Advance',
    fullName: 'Nintendo Game Boy Advance',
    type: 'handheld',
    extensions: ['.gba'],
    requiresBios: true,
    biosFiles: ['gba_bios.bin'],
    manufacturer: 'Nintendo',
    releaseYear: 2001,
  },
  nds: {
    code: 'nds',
    displayName: 'Nintendo DS',
    fullName: 'Nintendo DS',
    type: 'handheld',
    extensions: ['.nds'],
    requiresBios: false,
    manufacturer: 'Nintendo',
    releaseYear: 2004,
  },

  // === SEGA CONSOLES ===
  genesis: {
    code: 'genesis',
    displayName: 'Genesis',
    fullName: 'Sega Genesis / Mega Drive',
    type: 'console',
    extensions: ['.md', '.gen', '.smd'],
    requiresBios: false,
    manufacturer: 'Sega',
    releaseYear: 1988,
  },
  sms: {
    code: 'sms',
    displayName: 'Master System',
    fullName: 'Sega Master System',
    type: 'console',
    extensions: ['.sms'],
    requiresBios: false,
    manufacturer: 'Sega',
    releaseYear: 1986,
  },
  gg: {
    code: 'gg',
    displayName: 'Game Gear',
    fullName: 'Sega Game Gear',
    type: 'handheld',
    extensions: ['.gg'],
    requiresBios: false,
    manufacturer: 'Sega',
    releaseYear: 1990,
  },

  // === SONY ===
  // UNSUPPORTED - Requires special handling for multi-disc games and bin
  // psx: {
  //   code: "psx",
  //   displayName: "Sony PlayStation",
  //   type: "console",
  //   extensions: [".iso", ".chd", ".pbp"],
  //   requiresBios: true,
  //   biosFiles: ["scph1001.bin", "scph7001.bin", "scph5501.bin"],
  //   manufacturer: "Sony",
  //   releaseYear: 1994,
  // },

  // === ATARI ===
  atari2600: {
    code: 'atari2600',
    displayName: 'Atari 2600',
    fullName: 'Atari 2600',
    type: 'console',
    extensions: ['.a26'],
    requiresBios: false,
    manufacturer: 'Atari',
    releaseYear: 1977,
  },
  lynx: {
    code: 'lynx',
    displayName: 'Lynx',
    fullName: 'Atari Lynx',
    type: 'handheld',
    extensions: ['.lnx'],
    requiresBios: false,
    manufacturer: 'Atari',
    releaseYear: 1989,
  },

  // === SNK ===
  ngp: {
    code: 'ngp',
    displayName: 'Neo Geo Pocket',
    fullName: 'SNK Neo Geo Pocket',
    type: 'handheld',
    extensions: ['.ngp', '.ngc'],
    requiresBios: false,
    manufacturer: 'SNK',
    releaseYear: 1998,
  },

  // === ARCADE ===
  arcade: {
    code: 'arcade',
    displayName: 'Arcade',
    fullName: 'Arcade (MAME)',
    type: 'arcade',
    extensions: ['.zip'],
    requiresBios: false,
    manufacturer: 'Various',
    releaseYear: 1971,
  },
};
